vich_uploader:
  mappings:
    seo_og_image:
      uri_prefix: 'uploads/seo/og_images'
      upload_destination: '%kernel.project_dir%/public/uploads/seo/og_images'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      directory_namer: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true
